name: criptomoedas_brasilcripto
description: "Projeto de teste para vaga de desenvolvedor flutter na BrasilCard"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.71.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0  
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
